# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: bionic
language: rust
services: docker
sudo: required

addons:
  apt:
    packages:
    - libudev-dev
    - libhidapi-dev

# TODO Rust builds on stable by default, this can be
# overridden on a case by case basis down below.

env:
  global:
    # TODO Update this to match the name of your project.
    - CRATE_NAME=wooting-analog-sdk
    #- RUST_LOG=trace
    - >
      DISABLE_WINDOWS_DEFENDER=`powershell -Command
      Set-MpPreference -DisableArchiveScanning \\\$true`
    - >
      DISABLE_WINDOWS_DEFENDER=`powershell -Command
      Set-MpPreference -DisableRealtimeMonitoring \\\$true`
    - >
      DISABLE_WINDOWS_DEFENDER=`powershell -Command
      Set-MpPreference -DisableBehaviorMonitoring \\\$true`

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:

    - env: TARGET=x86_64-unknown-linux-gnu
    #- env: TARGET=x86_64-unknown-linux-musl

    # OSX
    #- env: TARGET=i686-apple-darwin
    #  os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Windows
    #- env: TARGET=x86_64-pc-windows-gnu

    - env: TARGET=x86_64-pc-windows-msvc
      os: windows

    #- env: TARGET=i686-pc-windows-msvc
    #  os: windows

    # Testing other channels
    # - env: TARGET=x86_64-pc-windows-msvc
    #   os: windows
    #   rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    # - env: TARGET=x86_64-apple-darwin
    #   os: osx
    #   rust: nightly

before_install:
  - set -e
  - rustup self update
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then rustup default stable-msvc   ; fi
  - rustup toolchain install nightly

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true
  - rustup show
  - which cargo-make || cargo install cargo-make

script:
  - bash ci/script.sh
  

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install -y wixtoolset --version 3.10.3.300702 || true; export PATH=$PATH";C:\Program Files (x86)\WiX Toolset v3.10\bin"               ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cargo make sign-win-installer --cwd wooting-analog-sdk -- --target $TARGET     ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cargo make build-deb --cwd wooting-analog-sdk -- --target $TARGET     ; fi

deploy:
  api_key:
    secure: eMiCXm1LYj/2c7xQ+j0wqKiRGHMevPMqJX4mshNm0VtmkyAQBCjdueTdMjXxB0FE0E3L9ts0RcxrBTXD96S74DdEKvw5kz0Bmn3XrUZfNJ0mK85s+c9wXycRKPyBlKzrPZOxmn8WUxQAx7Db1qAiOjK4IPpKp90GTFMKyOgGRpfCdM72UEyM1hEOs8++n1MRaW/5l/PsTRKdYVqmFT5oC7zh65MobWI6U7O3xkEkfQ1xrya2FJxMrEmQIVYlU1ADFAeUwtJJuocqhlJnmKhDWdUa9cNhpYzfDva+Fh95SSJuLPX8f9+DTya59Ts6Cqxtq6s7nEn1jU2awT11pmuuDewrztQRX5Tm1hTBQ8EhGN19w1lp+BEsnv7tidwG8zPKn0ME/j1dPGIO8Bz1zhMGqljqROvslv6PeEISO1aAizaPczZ6RaIGhiSsXdapzRLGrQRKY0Hkh80QLEMOVAayx1cUZC3GF7SAN4Wi7y3WXNsNnLdw7wPY7T1y7yAWXDplTASp4b+CmbdxLIfzOih/VR9dNwjn06bRfHHB1spGsyj+GzBThsRS069jix7lbTCEecpjNn9lLVUcspSl5d5MiOSiUHPdRcgPdG/6CLK2PeDoaM5avmlqs6GJXIkG218ju6/nSOq4bZhMB66N6Utc5Qyh63fSG9VTuvDdEwoh6OA=
  file_glob: true
  file:
    - $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
    - target/wix/*.msi
    - target/$TARGET/debian/*.deb
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true
  draft: true

cache:
  timeout: 1000
  cargo: true
before_cache:
  # Travis can't cache files that are not readable by "others"
  - travis_wait chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - develop
    - /^feature\/.*$/
    - /^hotfix\/.*$/
    - /^release\/.*$/

notifications:
  email:
    on_success: never
