[package]
name = "wooting-analog-wrapper"
version = "0.4.0"
authors = ["simon-wh <simon.whyte.lb@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "*"
libloading = "0.5.1"
wooting-analog-common = { path = "../wooting-analog-common"}

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]